lib/bot_evolution_tactics_web/router.ex
defmodule BotEvolutionTacticsWeb.Router do
  use BotEvolutionTacticsWeb, :router
  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin_session do
    plug BotEvolutionTacticsWeb.Plugs.Authentication
    plug BotEvolutionTacticsWeb.Plugs.LogAdminMetadata
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug BotEvolutionTacticsWeb.Plugs.LogApiMetadata
  end

  scope "/", BotEvolutionTacticsWeb do
    pipe_through :browser # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/v1", BotEvolutionTacticsWeb, as: :api_v1 do
    pipe_through :api

    get "/ping", Api.V1.PingController, :ping

    scope "/line" do
      post "/message/:bot_id", Api.V1.LineController, :message
    end
  end

  scope "/admin", BotEvolutionTacticsWeb.Admin, as: :admin do
    pipe_through [:browser, :admin_session]

    resources "/", RootController, only: [:index]
    resources "/staffs", StaffController
    resources "/bots", BotController
    resources "/dictionaries", DictionaryController
  end

  # Catch exception and report to Rollbar Service
  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    Rollbax.report(kind, reason, stacktrace)
  end

end

lib/bot_evolution_tactics_web/views/layout_view.ex
defmodule BotEvolutionTacticsWeb.LayoutView do
  use BotEvolutionTacticsWeb, :view

  def render_login_or_logout(conn) do
    case Guardian.Plug.current_resource(conn) do
      nil ->
        link "Login", to: session_path(conn, :new)
      current_staff ->
        link "Logout [#{current_staff.name}]", to: session_path(conn, :delete, current_staff.id), method: :delete
    end
  end
end

lib/bot_evolution_tactics_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BotEvolutionTactics Admin</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render BotEvolutionTacticsWeb.LayoutView, "nav.html", conn: @conn %>

    <div class="container-fluid">
      <div class="row">
        <%= render BotEvolutionTacticsWeb.LayoutView, "sidebar.html", conn: @conn %>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <%= render @view_module, @view_template, assigns %>
        </div>

      </div> <!-- /row -->

    </div> <!-- /container-fluid -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/bot_evolution_tactics_web/templates/layout/nav.html.eex
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">BotEvolutionTactics</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><%= render_login_or_logout(@conn) %></li>
      </ul>
    </div>

  </div> <!-- /container-fluid -->
</nav>

lib/bot_evolution_tactics_web/templates/layout/sidebar.html.eex
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><%= link "Home", to: admin_root_path(@conn, :index) %></li>
    <li><%= link "Staff", to: admin_staff_path(@conn, :index) %></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><%= link "Bot", to: admin_bot_path(@conn, :index) %></li>
    <li><%= link "Dictionary", to: admin_dictionary_path(@conn, :index) %></li>
  </ul>
</div>